#!/bin/bash

set -a
source /home/pi/.skycamrc
set +a

ffmpeg \
  -y -f h264 \
  -i <(raspivid -n -mm matrix -w 640 -h 480 -fps 25 -g 100 -t 0 -b 500000 -o -) \
  -c:v copy -map 0:0 -f flv \
  rtmp://$STREAM_URL/$STREAM_ID/stream
